### ISSUE TITLE
Updated ZF version shown as not the latest

### ISSUE THREAD

**Issue by Lansoweb** [zend-server-extensions/Z-Ray-ZF2#4]
Hi!
I've updated the ZF2 version on my ZS (8.0.1 development edition) and the Version tab shows it s not the latest, but both versions are the same (2.3.4). 
If i restart ZS via UI the issue persists. After i restart it from console (sudo /usr/local/zend/bin/zendctl.sh restart) it correctly shows IsLatest as "yes".
I know the problem is not necessary here, since it uses:
```php
zend_shm_cache_fetch('ZF2_version_isLatest');
```
but just reporting.

![versao234](https://cloud.githubusercontent.com/assets/2109813/5782790/3294c1a8-9da5-11e4-81f7-b35c4278b187.png)

**Comment by amitdar** [comment]
Hi,
So as you mentioned the ZF2 version isLatest is retrieved from `zend_shm_cache_fetch('ZF2_version_isLatest');` which get cached and takes some time until you see the new version. This is a typical ZF2 version check mechanize which we have no intent of changing in the scope of Z-Ray.
