### ISSUE TITLE
Fatal error: Class 'Zend\Version\Version' not found

### ISSUE THREAD

**Issue by antonmakarenko** [zend-server-extensions/Z-Ray-ZF2#5]
I have a Zend Server 8.0.1 Build 94158 and created a virtual host for my application. The latter is a ZF2-based web-application. It loads the Zend Framework following components via Composer:
```
        "zendframework/zend-stdlib": "2.3.1",
        "zendframework/zend-code": "2.3.1",
        "zendframework/zend-server": "2.3.1",
        "zendframework/zend-soap": "2.3.1",
        "zendframework/zend-uri": "2.3.1",
        "zendframework/zend-validator": "2.3.1",
        "zendframework/zend-console": "2.3.1",
        "zendframework/zend-modulemanager": "2.3.1",
        "zendframework/zend-mvc": "2.3.1",
        "zendframework/zend-text": "2.3.1",
        "zendframework/zend-eventmanager": "2.3.1",
        "zendframework/zend-view": "2.3.1",
        "zendframework/zend-servicemanager": "2.3.1",
        "zendframework/zend-json": "2.3.1",
        "zendframework/zend-config": "2.3.1",
        "zendframework/zend-form": "2.3.1",
        "zendframework/zend-di": "2.3.1",
        "zendframework/zend-serializer": "2.3.1",
        "zendframework/zend-log": "2.3.1",
        "zendframework/zend-http": "2.3.1",
```
As result of loading all these components by Composer, the `zendframework/zend-version` is not in the `vendor` directory. My application is not using any other autoloader except from Composer's.

So when I try to run it, I get this fatal error:
```

Fatal error: Class 'Zend\Version\Version' not found in C:\work\zend_server\ZendServer\data\zray\extensions\ZF2\zray.php on line 137
```

Inspecting the contents of Zend Server directory shows that it happens to bundle a copy of entire ZF2: `C:\work\zend_server\ZendServer\data\libraries\Zend_Framework_2\2.3.3\library\Zend`

The include path from `phpinfo()` (not sure if it is supposed to help though):
```
.;C:\work\zend_server\ZendServer\share\ZendFramework\library
```

Questions:
- Is Z-Ray relying on my application to provide all components of Zend Framework 2 and take care of autoloading?
- Is Z-Ray supposed to use the Zend Framework bundled with Zend Server? Does it have own autoloader? Does it have something to do with include path?

**Comment by amitdar** [comment]
Z-Ray itself does not rely on your application's code or library. The ZF2 extension for Z-Ray trying to fetch information about the ZF2 of your application, and by doing that it search for ZF2/Version class. I've just committed a fix for cases where this class doesn't exists.
