### ISSUE TITLE
Version check - Fail gracefully if server is offline

### ISSUE THREAD

**Issue by mkherlakian** [zend-server-extensions/Z-Ray-ZF2#8]
The extension does an automatic latest version check for ZF2

https://github.com/zend-server-extensions/Z-Ray-ZF2/blob/4cbfb5f23705cb77cd36c4e8d20c48fc1bf5d900/zray.php#L40

This causes a timeout and ultimately an error on the page. Could we implement a graceful failure if no connection is detected, with a relatively short timeout (5 seconds) and cache the failure to prevent it from being retried?

Development machines are often offline, so that would help.

**Comment by amitdar** [comment]
Fixed in https://github.com/zend-server-extensions/Z-Ray-ZF2/commit/c68a7914eada7104cf22d5ee3a7a93d3f6f6dd68

Thanks!
